name: Bug Report
description: Report an issue to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Modpack version
      description: 'Latest' is not a valid answer, please write the exact version number.
      placeholder: Release xxx **or** Beta xxx
    validations:
      required: false
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue.
    validations:
      required: true
  - type: dropdown
    id: modified
    attributes:
      label: Have you modified the modpack?
      description: Have you added mods, changed configs, changed scripts or similar?
      options:
        - no
        - yes
      default: 0
    validations:
      required: true
  - type: textarea
    id: modified_yes
    attributes:
      label: User Modifications
      description: If you answered "Yes" above, please briefly explain what you have modified. Added mods are particularly important.
    validations:
      required: false
  - type: dropdown
    id: play
    attributes:
      label: Did the issue happen in singleplayer or on a server?
      options:
        - singleplayer
        - sever
        - both
      default: 0
    validations:
      required: true
