name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: version
    attributes:
      label: Modpack Version
      placeholder: Beta xxx or Release xxx
      description: Specific Modpack Version
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: Describe your issue
    validations:
      required: true
  - type: dropdown
    id: modified
    attributes:
      label: Have you modified the modpack?
      description: Have you added mods, changed configs, changed scripts or similar?
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: true
  - type: textarea
    id: modifications
    attributes:
      label: User Modifications
      description: If you answered "Yes" above, please briefly explain what you have modified. Added mods are particularly important.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
