
#Common settings for the Sifter
[sifter]
	#The minimum speed required to run the sifter
	#Range: 1.0 ~ 254.0
	sifterMinSpeed = 10.0

#Common settings for the Mesh
[mesh]
	#The max durability of the mesh if meshes are set to take damage
	#Range: > 1
	meshDurability = 256
	#If the mesh should have a chance to take damage whenever a recipe finishes processing
	meshTakeDamage = true

